### ISSUE TITLE
The link to multishot solving slides is wrong

### ISSUE THREAD

**Issue by iensen** [potassco/potassco.github.io#2]
Hello,

I believe the link to PDF file for multi-shot solving slides here: https://potassco.github.io/teaching/
[Mult-shot Solving LaTeX Bundle PDF]
is incorrect. The slides there are not about multi-shot solving.

Thanks.

**Comment by tortinator** [comment]
Fixed! Reload or empty browser cache to get it -tortinator

**Comment by tortinator** [comment]
Just closing the issue :)

**Comment by iensen** [comment]
Thank you!
