### ISSUE TITLE
teaspoon

### ISSUE THREAD

**Issue by tortinator** [potassco/potassco.github.io#24]
Created repo at https://github.com/potassco/teaspoon

ToDo 
- link to repo
- add publication (see README.md in repo)

**Comment by tortinator** [comment]
@rkaminsk I would need your advise on how to put the literature link

**Comment by rkaminsk** [comment]
Just do

    grep -R publicationurl .

Citations are used all over the place.

Please publish large tarballs with experiments as release assets.
