### ISSUE TITLE
Old Google+ links

### ISSUE THREAD

**Issue by sthiele** [potassco/potassco.github.io#26]
There are some places on the website with old links to Google plus.
These should be removed. Maybe think about Twitter as an alternative?

**Comment by rkaminsk** [comment]
I could add change links but @tortinator is Twitter and Facebook ambassador. Can you provide the links you want to put?

PS: Please let's not put any like buttons. Those spy.

**Comment by tortinator** [comment]
Moin. Would be good to get rid of these old links.
Here is out Twitter url,  https://twitter.com/potassco, which we might add instead.
Having FB and Twitter should be ok, can't handle more anyway.

**Comment by rkaminsk** [comment]
Thanks @sthiele, I merged.
