### ISSUE TITLE
Run on Ctrl+Enter

### ISSUE THREAD

**Issue by stefnotch** [potassco/potassco.github.io#41]
It'd be lovely if the demo at https://github.com/potassco/potassco.github.io/blob/be73b6aaae1e482f8701a3a8764ae8ec8a3a6962/js/clingo-module.js would execute clingo when one hits `Ctrl`+`Enter`

I'm using this script as a workaround for now
```
document.querySelector("#input").addEventListener("keydown", (ev) => {
  if(ev.key === "Enter" && ev.ctrlKey) {
    solve();
  }
})
```

**Comment by rkaminsk** [comment]
> It'd be lovely if the demo at https://github.com/potassco/potassco.github.io/blob/be73b6aaae1e482f8701a3a8764ae8ec8a3a6962/js/clingo-module.js would execute clingo when one hits `Ctrl`+`Enter`
> 
> I'm using this script as a workaround for now
> 
> ```
> document.querySelector("#input").addEventListener("keydown", (ev) => {
>   if(ev.key === "Enter" && ev.ctrlKey) {
>     solve();
>   }
> })
> ```

My JavaScript is rusty and I have to learn it anew every time I come in touch with it. Could you open a PR, please? The code is here:
- https://github.com/potassco/potassco.github.io
- https://github.com/potassco/potassco.github.io/blob/master/js/clingo-module.js
