### ISSUE TITLE
Please mention on the website that packages are available for FreeBSD

### ISSUE THREAD

**Issue by yurivict** [potassco/potassco.github.io#45]
The [website](https://potassco.org/clingo/) can mention that clingo package is available on FreeBSD: https://www.freshports.org/math/clingo/

**Comment by rkaminsk** [comment]
I'll take care later.

**Comment by yurivict** [comment]
@rkaminsk It would be more accurate to say "Packages for clingo are available for FreeBSD-based distributions".

**Comment by rkaminsk** [comment]
> @rkaminsk It would be more accurate to say "Packages for clingo are available for FreeBSD-based distributions".

Currently there are only packages for FreeBSD. The idea was to have a BSD section. Maybe there will be OpenBSD packages at some point.

**Comment by yurivict** [comment]
This link is only for FreeBSD and derived systems. Once OpenBSD package arrives it can be listed in addition to FreeBSD. The systems are currently unrelated - their ports/packages are entirely different.

**Comment by rkaminsk** [comment]
> This link is only for FreeBSD and derived systems. Once OpenBSD package arrives it can be listed in addition to FreeBSD. The systems are currently unrelated - their ports/packages are entirely different.

I understand. The same holds true for the Linux distributions above. You cannot use an Arch package on Ubuntu and vice versa. If you explicitly want to mention FreeBSD  just provide a PR.
